### ISSUE TITLE
Переделать action на ООП и процессоры

### ISSUE THREAD

**Issue by pavel-one** [pavel-one/modSizeControl#1]

**Comment by pavel-one** [comment]
@GulomovCreative потестировал несколько кейсов, вроде ок, если тебя по js все устраивает, закрывай issue :)

**Comment by pavel-one** [comment]
@GulomovCreative Также хорошо бы там вынести в лексиконы все ошибки #9

**Comment by GulomovCreative** [comment]
@pavel-one По js всё потрясно!

**Comment by pavel-one** [comment]
Закрываю
