### ISSUE TITLE
По всей видимости на Linux считает неправильно, нужно исправить

### ISSUE THREAD

**Issue by GulomovCreative** [pavel-one/modSizeControl#16]

**Comment by pavel-one** [comment]
The "apparent size" of a file is how much valid data is actually in the file. It is the actual amount of data that can be read from the file. Block-oriented devices can only store in terms of blocks, not bytes. As a result, the disk usage is always rounded up to the next highest block. A "block" in this case may not equate to a physical block on the storage device, either, depending on how the file system allocates space.

**Comment by GulomovCreative** [comment]
@pavel-one Закрываю тогда
